version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart: always
  
  api:
    build: 
      context: .
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - MONGODB_DB=users
      - MONGODB_HOST=mongodb
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
    restart: always
    volumes:
      - ./application:/app/application
    depends_on:
      - mongodb