{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "restapi-flask.fullname" . }}
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  ingressClassName: alb
  rules:
  - host: api.joselucas.me 
    http:
      paths:
      - backend:
          service:
            name: {{ include "restapi-flask.fullname" . }}
            port:
              number: {{ .Values.appPort | default 5000}}
        path: /
        pathType: Prefix
{{ end }}