apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: restapi-flask-ingress
spec:
  rules:
  - host: api.localhost.com
    http:
      paths:
      - backend:
          service:
            name: restapi-flask
            port:
              number: 5000
        path: /
        pathType: Prefix
