name: Deploy Kubernetes

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: make test
  
  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::298562162259:role/restapi-gh-actions-oidc-role
          role-session-name: samplerolesession
          aws-region: us-west-2
      - name: Build Docker image
        run: |
          aws sts get-caller-identity

          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin ${ecr_registry}

          sha=${{ github.sha }}
          short_sha=${sha:0:7}

          docker build -t ${ecr_registry}/${ecr_repository}:dev-${short_sha} .
          docker push ${ecr_registry}/${ecr_repository}:dev-${short_sha}
